version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    target-branch: develop

    groups:
      spring-boot:
        patterns:
          - "org.springframework*"
      testing:
        patterns:
          - "*junit*"
          - "*mockito*"
      etc:
        patterns:
          - "*"
        exclude-patterns:
          - "org.springframework*"
          - "*junit*"
          - "*mockito*"

    assignees:
      - Kairyx-dev
    reviewers:
      - Kairyx-dev

    commit-message:
      prefix: "[Dependabot]"
      include: scope

    labels:
      - "dependencies"

  # GitHub Actions 의존성 관리 추가
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 3
    target-branch: develop
    assignees:
      - Kairyx-dev
    reviewers:
      - Kairyx-dev
    commit-message:
      prefix: "[Dependabot-CI]"
      include: scope

    groups:
      actions-deps:
        patterns:
          - "*"

    labels:
      - "dependencies"