name: Build And push

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # chckout
      - name: Checkout repository
        uses: actions/checkout@v5

      # jdk set up
      - name: JDK 21 set-up
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      # grant gradle script
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      # docker login
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ADDRESS }}
          password: ${{ secrets.DOCKER_PAT }}

      # docker build and push
      - name: deploy jib
        shell: bash
        env:
          DOCKER_ID: ${{ secrets.DOCKER_USER }}
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
        run: >
          ./gradlew :boot:jib
          -DdockerId="$DOCKER_ID"
          -DdockerRepository="$DOCKER_REPOSITORY"

      # docker restart
      - name: Container restart
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEPLOY_IP }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            python3 ~/docker/korConverter/script/restart.py