name: Build And push

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # chckout
      - name: Checkout repository
        uses: actions/checkout@v5

      # jdk set up
      - name: JDK 21 set-up
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'corretto'

      # grant gradle script
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      # docker build and push
      - name: deploy jib
        shell: bash
        run: >
          ./gradlew :boot:jibBuildTar

      - name: Copy files SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DEPLOY_IP }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: "korConverter/boot/build/jib-image.tar"
          target: "~/docker/korConverter/image"
          rm: true
          strip_components: 3

      # docker restart
      - name: Container restart
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: ${{ secrets.DEPLOY_IP }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            docker load -i ~/docker/korConverter/image/jib-image.tar
            python3 ~/docker/korConverter/script/restart.py